{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.7.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.71"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.71"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.71"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9.jar",
          "url": "spring-boot-starter-tomcat-2.7.9.jar",
          "size": 4796,
          "sha512": "2e78b32735e95b07dda19bde76913eb2df885637f744f96cd9084263e40b86368685013e8752db44cb04f26c091df82e799a26b85864a434d1973157185d076d",
          "sha256": "d970c2c4baccea9cf1bcb99ecd0340b3d1a2a4d1a14b07b865a56965754579d5",
          "sha1": "a1076e6ffa1d771d3ccd18e72280317a152323e8",
          "md5": "4c540f28a40c2f7cc773d29033c3c82c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.71"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.71"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.71"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9.jar",
          "url": "spring-boot-starter-tomcat-2.7.9.jar",
          "size": 4796,
          "sha512": "2e78b32735e95b07dda19bde76913eb2df885637f744f96cd9084263e40b86368685013e8752db44cb04f26c091df82e799a26b85864a434d1973157185d076d",
          "sha256": "d970c2c4baccea9cf1bcb99ecd0340b3d1a2a4d1a14b07b865a56965754579d5",
          "sha1": "a1076e6ffa1d771d3ccd18e72280317a152323e8",
          "md5": "4c540f28a40c2f7cc773d29033c3c82c"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9.jar",
          "url": "spring-boot-starter-tomcat-2.7.9.jar",
          "size": 4796,
          "sha512": "2e78b32735e95b07dda19bde76913eb2df885637f744f96cd9084263e40b86368685013e8752db44cb04f26c091df82e799a26b85864a434d1973157185d076d",
          "sha256": "d970c2c4baccea9cf1bcb99ecd0340b3d1a2a4d1a14b07b865a56965754579d5",
          "sha1": "a1076e6ffa1d771d3ccd18e72280317a152323e8",
          "md5": "4c540f28a40c2f7cc773d29033c3c82c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9.jar",
          "url": "spring-boot-starter-tomcat-2.7.9.jar",
          "size": 4796,
          "sha512": "2e78b32735e95b07dda19bde76913eb2df885637f744f96cd9084263e40b86368685013e8752db44cb04f26c091df82e799a26b85864a434d1973157185d076d",
          "sha256": "d970c2c4baccea9cf1bcb99ecd0340b3d1a2a4d1a14b07b865a56965754579d5",
          "sha1": "a1076e6ffa1d771d3ccd18e72280317a152323e8",
          "md5": "4c540f28a40c2f7cc773d29033c3c82c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.7.9-javadoc.jar",
          "size": 4745,
          "sha512": "6760e83de4a2636a0778808e04c9a2434fb9071802155c699205d61d8aa54606c3b4495c04cf38e25088e39ba7910ac1d6e5de1672d450274e4910653ce6545a",
          "sha256": "d61dbfd055118acfaf3099ef1225640d9eb93317b6da6db9771259a3c5eed964",
          "sha1": "fdf6ee3c46e47feec8a790330d2ad6973260247f",
          "md5": "bcd51c7e8c2d3e20b22b1bf3cf4f49a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.9-sources.jar",
          "url": "spring-boot-starter-tomcat-2.7.9-sources.jar",
          "size": 4743,
          "sha512": "8fe376fc696b8e00f2728ff7c77b1bbf34b09413890bbed2583198b3c62acded825c31c0fb9d8053bc6f9cc74fc293889a25bdbefe46793898d9efb14f53cd81",
          "sha256": "807f8626f3d156cdc690d47d51deb5607cdfeaf2b8301a8157f12176de92cb49",
          "sha1": "3d247dbead4a3cf00ecb747c1bdc32c1cbc05c7d",
          "md5": "799734ad1cbee912917f8f101b9eb28d"
        }
      ]
    }
  ]
}
