{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.4.3.jar",
          "url": "spring-boot-starter-3.4.3.jar",
          "size": 4769,
          "sha512": "555955b51daa89662af3c0a40850c4f37058cbe6290a1be3088db61843b48ce7fed3948019014d84af4d26765472dabe1defac47a3c7ded6e6d3e05c9529dccd",
          "sha256": "73b48525c88afb61f6645d78de5bb0c7b366ac201657d36f814758c1591b793f",
          "sha1": "0247fdc05cd6de013c3fd26628fa221dd095b391",
          "md5": "409819a98da22207ff0a3707429ee3cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.4.3.jar",
          "url": "spring-boot-starter-3.4.3.jar",
          "size": 4769,
          "sha512": "555955b51daa89662af3c0a40850c4f37058cbe6290a1be3088db61843b48ce7fed3948019014d84af4d26765472dabe1defac47a3c7ded6e6d3e05c9529dccd",
          "sha256": "73b48525c88afb61f6645d78de5bb0c7b366ac201657d36f814758c1591b793f",
          "sha1": "0247fdc05cd6de013c3fd26628fa221dd095b391",
          "md5": "409819a98da22207ff0a3707429ee3cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.4.3-javadoc.jar",
          "url": "spring-boot-starter-3.4.3-javadoc.jar",
          "size": 4769,
          "sha512": "47a436314ea37f0dc0b0fa9d64add64a891f5e937d2aa7b01a842e4e844e1c81aab7b7c0767fb864f3aa357182726a14754276cb739ef20718256c02dd7f9a8e",
          "sha256": "0cdb3083a85fabe67b0addd7bc66c9ae7ac3757a352394902d0065b9a506eb92",
          "sha1": "c66312a30b815d3a9f94b4f6fb603f3630a41a17",
          "md5": "109add292b64af06b52f35f8fb61ca2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.4.3-sources.jar",
          "url": "spring-boot-starter-3.4.3-sources.jar",
          "size": 4769,
          "sha512": "47a436314ea37f0dc0b0fa9d64add64a891f5e937d2aa7b01a842e4e844e1c81aab7b7c0767fb864f3aa357182726a14754276cb739ef20718256c02dd7f9a8e",
          "sha256": "0cdb3083a85fabe67b0addd7bc66c9ae7ac3757a352394902d0065b9a506eb92",
          "sha1": "c66312a30b815d3a9f94b4f6fb603f3630a41a17",
          "md5": "109add292b64af06b52f35f8fb61ca2f"
        }
      ]
    }
  ]
}
