{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.25"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9.jar",
          "size": 4759,
          "sha512": "efdbab2cf0ca8cc95ae50cd781d5e8b0f82b3b58fb1126349fdbed5b282cd7ae4f26f94e0844b8ca0e1fd424ef220e8e3484ec306b436d75d35502a6377f6b1a",
          "sha256": "facfb5d6aa6e07b63c85dfaa00c351702da5d9566d60838e6101b3cd5703f634",
          "sha1": "5af4a206fd4eaac881b7d96ca1ef19b2111a355c",
          "md5": "e9c74f7bf54dad3b529dc33d243e2cb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.25"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9.jar",
          "size": 4759,
          "sha512": "efdbab2cf0ca8cc95ae50cd781d5e8b0f82b3b58fb1126349fdbed5b282cd7ae4f26f94e0844b8ca0e1fd424ef220e8e3484ec306b436d75d35502a6377f6b1a",
          "sha256": "facfb5d6aa6e07b63c85dfaa00c351702da5d9566d60838e6101b3cd5703f634",
          "sha1": "5af4a206fd4eaac881b7d96ca1ef19b2111a355c",
          "md5": "e9c74f7bf54dad3b529dc33d243e2cb9"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9.jar",
          "size": 4759,
          "sha512": "efdbab2cf0ca8cc95ae50cd781d5e8b0f82b3b58fb1126349fdbed5b282cd7ae4f26f94e0844b8ca0e1fd424ef220e8e3484ec306b436d75d35502a6377f6b1a",
          "sha256": "facfb5d6aa6e07b63c85dfaa00c351702da5d9566d60838e6101b3cd5703f634",
          "sha1": "5af4a206fd4eaac881b7d96ca1ef19b2111a355c",
          "md5": "e9c74f7bf54dad3b529dc33d243e2cb9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9.jar",
          "size": 4759,
          "sha512": "efdbab2cf0ca8cc95ae50cd781d5e8b0f82b3b58fb1126349fdbed5b282cd7ae4f26f94e0844b8ca0e1fd424ef220e8e3484ec306b436d75d35502a6377f6b1a",
          "sha256": "facfb5d6aa6e07b63c85dfaa00c351702da5d9566d60838e6101b3cd5703f634",
          "sha1": "5af4a206fd4eaac881b7d96ca1ef19b2111a355c",
          "md5": "e9c74f7bf54dad3b529dc33d243e2cb9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9-javadoc.jar",
          "size": 4750,
          "sha512": "fe137f48859bf6740bfe1bde0bf7b7a7f0205c259449bb6673909b05f3e3f1c3a146f6346e4c5be4f884e1a8445f644854cdac064a867e8dbd65e17fdf5f6dd0",
          "sha256": "a758b1d92bcd1fb162ee7d12d3c160303384700b12134f4887025c31e2048d92",
          "sha1": "86ee42facdd5a727082d72dcd8144a72f0c816b2",
          "md5": "7cee807f88a32fde347f1cc71e84be0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.9-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.9-sources.jar",
          "size": 4747,
          "sha512": "47fffbb77b3f5797e457d0c82fc1ff43554b7244d6c8ffd28d096b13fb0643e16372cacf7e238f375cdb0c73b68d38b05306647f90bb7c7bdd8e0cf96eb5bb4e",
          "sha256": "be507fa79374231c37abe00d34b02a21af74d8fb4944616cbd6d513d3dd4e214",
          "sha1": "0fb552bd771d745fc80039b67dd245573ae6aa21",
          "md5": "59e7b29e97501b19cdf985b9052cca8b"
        }
      ]
    }
  ]
}
