{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.25"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.25"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.25.jar",
          "url": "spring-web-5.3.25.jar",
          "size": 1642784,
          "sha512": "08954eb4e21e5e9e07ea62c784e2e3843795ec8e2d02e2969ae5b076567316dd2b5cf5fb460108e5474c50d871861a0dd878cac6811fdecb634199fdc59a75a7",
          "sha256": "d12ae84305e2c0cf474417492927bb8fa22227990a3815b21d9cf47f5fa05182",
          "sha1": "c69815e7931cd3ce7f19cc8028fd1c36626120d6",
          "md5": "c875b24c532e1b089ea3b1b09da61834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.25"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.25"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.25.jar",
          "url": "spring-web-5.3.25.jar",
          "size": 1642784,
          "sha512": "08954eb4e21e5e9e07ea62c784e2e3843795ec8e2d02e2969ae5b076567316dd2b5cf5fb460108e5474c50d871861a0dd878cac6811fdecb634199fdc59a75a7",
          "sha256": "d12ae84305e2c0cf474417492927bb8fa22227990a3815b21d9cf47f5fa05182",
          "sha1": "c69815e7931cd3ce7f19cc8028fd1c36626120d6",
          "md5": "c875b24c532e1b089ea3b1b09da61834"
        }
      ]
    }
  ]
}
