{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.3.jar",
          "url": "spring-beans-6.2.3.jar",
          "size": 882688,
          "sha512": "d5bf5221762b9dbc45d8b3c2d2cb1939829747d086cbd2e9e4656d274eeb1464cdb959cb37acd3edd8fc9b01d7a4dd34e0a3f9ad952475b4293617c808260366",
          "sha256": "4e289d6c0aa3ea74633005dae06d7cc827510e5b840d68bfcebdcf0bdd363f44",
          "sha1": "de660324c90e9b015886d85c746860478fa7d99c",
          "md5": "cf67cef8cdb42ffffda9c14dcc8ff732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.3.jar",
          "url": "spring-beans-6.2.3.jar",
          "size": 882688,
          "sha512": "d5bf5221762b9dbc45d8b3c2d2cb1939829747d086cbd2e9e4656d274eeb1464cdb959cb37acd3edd8fc9b01d7a4dd34e0a3f9ad952475b4293617c808260366",
          "sha256": "4e289d6c0aa3ea74633005dae06d7cc827510e5b840d68bfcebdcf0bdd363f44",
          "sha1": "de660324c90e9b015886d85c746860478fa7d99c",
          "md5": "cf67cef8cdb42ffffda9c14dcc8ff732"
        }
      ]
    }
  ]
}
