{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.3.jar",
          "url": "spring-core-6.2.3.jar",
          "size": 1959100,
          "sha512": "a271bb8e8eb9b847e23f164e0cd4246d5032f8180259d1237679faaa78e68f0c123a6fd25dfd49e1939121f911d7e670dcf29c383f9ccbd87938a0bccce404ba",
          "sha256": "49531684df2304f0e611f775faba79273c77504eb7d856592d830e2389e9eb14",
          "sha1": "13ec11e345b915d7ceea37446f1b1eefdcaad62c",
          "md5": "abde59c90579b665d6170aafd200d3d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.3.jar",
          "url": "spring-core-6.2.3.jar",
          "size": 1959100,
          "sha512": "a271bb8e8eb9b847e23f164e0cd4246d5032f8180259d1237679faaa78e68f0c123a6fd25dfd49e1939121f911d7e670dcf29c383f9ccbd87938a0bccce404ba",
          "sha256": "49531684df2304f0e611f775faba79273c77504eb7d856592d830e2389e9eb14",
          "sha1": "13ec11e345b915d7ceea37446f1b1eefdcaad62c",
          "md5": "abde59c90579b665d6170aafd200d3d3"
        }
      ]
    }
  ]
}
