{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.3.jar",
          "url": "spring-boot-starter-logging-3.4.3.jar",
          "size": 4761,
          "sha512": "1c2f7c85b183cfffb3cff211947b2f8dd3d3a2b584a03348569e7616c79e8258ffbdc6c39193c8c501fba2774502594f4e7da2760def2a2bdb7267b6055d295e",
          "sha256": "c65df0c3a6dd1cc992f9bed2ccf2e087b72be0ab5031d5085e4079d653de4d52",
          "sha1": "e5aee6af32c2dbcc9fb379bcd6c5e5b931db93f1",
          "md5": "1141702822dcf9c83ed2f3e2ece312a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.3.jar",
          "url": "spring-boot-starter-logging-3.4.3.jar",
          "size": 4761,
          "sha512": "1c2f7c85b183cfffb3cff211947b2f8dd3d3a2b584a03348569e7616c79e8258ffbdc6c39193c8c501fba2774502594f4e7da2760def2a2bdb7267b6055d295e",
          "sha256": "c65df0c3a6dd1cc992f9bed2ccf2e087b72be0ab5031d5085e4079d653de4d52",
          "sha1": "e5aee6af32c2dbcc9fb379bcd6c5e5b931db93f1",
          "md5": "1141702822dcf9c83ed2f3e2ece312a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.3-javadoc.jar",
          "url": "spring-boot-starter-logging-3.4.3-javadoc.jar",
          "size": 4761,
          "sha512": "7defeaac99524a231cf3a90a189146d7908caf29868c37233c35f83e49edd94d0e101871aec40316dd0a5421a5da14cf6685b8873bb1be17dcd46ff8abd7dced",
          "sha256": "2aab3ee71ab9966a570b9ff2427ae4e8d05479959f7a5b9fa4c3b9805f112b2a",
          "sha1": "9ea3a517e48251ef4d24160d567091fd3d369a13",
          "md5": "a8c78aba559b04a66d8763c84d43dfa7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.3-sources.jar",
          "url": "spring-boot-starter-logging-3.4.3-sources.jar",
          "size": 4761,
          "sha512": "7defeaac99524a231cf3a90a189146d7908caf29868c37233c35f83e49edd94d0e101871aec40316dd0a5421a5da14cf6685b8873bb1be17dcd46ff8abd7dced",
          "sha256": "2aab3ee71ab9966a570b9ff2427ae4e8d05479959f7a5b9fa4c3b9805f112b2a",
          "sha1": "9ea3a517e48251ef4d24160d567091fd3d369a13",
          "md5": "a8c78aba559b04a66d8763c84d43dfa7"
        }
      ]
    }
  ]
}
