{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.3.jar",
          "url": "spring-boot-starter-web-3.4.3.jar",
          "size": 4805,
          "sha512": "4b3de2c131cb8e6d49c08bbe2a6b6eabb013d1abfab9c00a6053d74c7608f5270ed5de2e96fba799d64eddc2183350035be083a7fb79b3d9607afed1fd2ed19d",
          "sha256": "ada24c1526c9a20d8fdbab5d4f3bc4d779495a317cff3a7d789fa87e33628685",
          "sha1": "87e7a401e7d249fefc7f372f5681e8620234624c",
          "md5": "3800f02907aa6d0e7573c2c0061d9bda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.3.jar",
          "url": "spring-boot-starter-web-3.4.3.jar",
          "size": 4805,
          "sha512": "4b3de2c131cb8e6d49c08bbe2a6b6eabb013d1abfab9c00a6053d74c7608f5270ed5de2e96fba799d64eddc2183350035be083a7fb79b3d9607afed1fd2ed19d",
          "sha256": "ada24c1526c9a20d8fdbab5d4f3bc4d779495a317cff3a7d789fa87e33628685",
          "sha1": "87e7a401e7d249fefc7f372f5681e8620234624c",
          "md5": "3800f02907aa6d0e7573c2c0061d9bda"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.3-javadoc.jar",
          "url": "spring-boot-starter-web-3.4.3-javadoc.jar",
          "size": 4805,
          "sha512": "19d6c26aed30bed6e8b20e2596c39118bf2653e2616c50d057bff464d167dbcce185034c23088d1fb995796b45f7188e92a390a750f0293479ff6d5cffabea0a",
          "sha256": "993a8cfef330386cf6d2d928030db2014b608851aa9be65847ec5adf0f852c11",
          "sha1": "7888c661b53889be91f104bdcb256219363d3c77",
          "md5": "7d37c9a80b3e10f6a12e6bdc2a249208"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.3-sources.jar",
          "url": "spring-boot-starter-web-3.4.3-sources.jar",
          "size": 4805,
          "sha512": "19d6c26aed30bed6e8b20e2596c39118bf2653e2616c50d057bff464d167dbcce185034c23088d1fb995796b45f7188e92a390a750f0293479ff6d5cffabea0a",
          "sha256": "993a8cfef330386cf6d2d928030db2014b608851aa9be65847ec5adf0f852c11",
          "sha1": "7888c661b53889be91f104bdcb256219363d3c77",
          "md5": "7d37c9a80b3e10f6a12e6bdc2a249208"
        }
      ]
    }
  ]
}
