{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.3.jar",
          "url": "spring-boot-3.4.3.jar",
          "size": 1770003,
          "sha512": "20a2a09d9fcc4125fa92d2db9173b6ac1bee4507a0fa7196a634678b9e32f5036ea34958a26fb4c3ba307bda3b13130ded69b871087a0d749305854cd15b4242",
          "sha256": "418a6afd2920afe62fc5c09cc46b485a7a6fdd09e167f0aed5a2347809eb560c",
          "sha1": "a7138bcecd59ed27660b3894a7812d65db4951e6",
          "md5": "286003693578e80380c533959783bc14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.3.jar",
          "url": "spring-boot-3.4.3.jar",
          "size": 1770003,
          "sha512": "20a2a09d9fcc4125fa92d2db9173b6ac1bee4507a0fa7196a634678b9e32f5036ea34958a26fb4c3ba307bda3b13130ded69b871087a0d749305854cd15b4242",
          "sha256": "418a6afd2920afe62fc5c09cc46b485a7a6fdd09e167f0aed5a2347809eb560c",
          "sha1": "a7138bcecd59ed27660b3894a7812d65db4951e6",
          "md5": "286003693578e80380c533959783bc14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.3-javadoc.jar",
          "url": "spring-boot-3.4.3-javadoc.jar",
          "size": 2464645,
          "sha512": "54ea604cf6e5b5201aa4e4d8098c7353a123746fd550f273df7d668ffbb03c8de46f62a4fa7fd180e94e061bf420f588599a0d6db6754277723d9035106a24e3",
          "sha256": "bcea867671716e815a752a800c9d09cf0a3dda67dc8a2f77905ee4ff5e50bb25",
          "sha1": "67ab4f2203b4dc340c0aba2be9e9f7da13732b0e",
          "md5": "f87c77c14a65cb9e5b991638c85346bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.3-sources.jar",
          "url": "spring-boot-3.4.3-sources.jar",
          "size": 1185919,
          "sha512": "db6e48314c1af01aeb4dc5874625b2e78687c172a59c65f2d65cebe0d46e55f61ebec5e0f07ef72a62cc1ebf5b6f54a22211d740050d73b5ba0cb69e522bdedb",
          "sha256": "109e7d0fe0d17f6062c0751f6efd77a27438cbf3db0a0ba9d5646ac63836d259",
          "sha1": "2aa910fdcfaf5ea89d6ff276f7c54f94db874771",
          "md5": "c3608daedbbed1fe9e9748baf20e5bb0"
        }
      ]
    }
  ]
}
