server:
  port: 8081
  name: store-admin

spring:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: store-admin

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
    host: localhost
    port: 5672
    username: admin
    password: 1234

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
