{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "6.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.4.3.jar",
          "url": "spring-security-core-6.4.3.jar",
          "size": 610218,
          "sha512": "ff6683e2c509aed25c6a98344efde01b7c11dd0e19629c88bc3b42ff7dfaf8abde01606e234f326ca78733ee62def2afb57cf07cf805cb1ed25560a558c72a66",
          "sha256": "5f618f51c5f8d1a77447f3cb4e8c8cf420018a9fe2555af3f070b5873f3b10b4",
          "sha1": "3023090cb32ecfe266726edc498ae8cb112f4e7f",
          "md5": "46ad3a78c21b3bea16af126ca56fd3ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.4.3.jar",
          "url": "spring-security-core-6.4.3.jar",
          "size": 610218,
          "sha512": "ff6683e2c509aed25c6a98344efde01b7c11dd0e19629c88bc3b42ff7dfaf8abde01606e234f326ca78733ee62def2afb57cf07cf805cb1ed25560a558c72a66",
          "sha256": "5f618f51c5f8d1a77447f3cb4e8c8cf420018a9fe2555af3f070b5873f3b10b4",
          "sha1": "3023090cb32ecfe266726edc498ae8cb112f4e7f",
          "md5": "46ad3a78c21b3bea16af126ca56fd3ed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.4.3-javadoc.jar",
          "url": "spring-security-core-6.4.3-javadoc.jar",
          "size": 1434186,
          "sha512": "ef10998e80f13ddae13866f790678c0b25f84c68ea2b8a4c94d2424206286084c9b95b6db492d00887c6c49b30f99741675a7e34ecbde0bd6e7b6253832f1e00",
          "sha256": "62226301cb9f17fc2b4dceeb3e8839029e9123d48aa04f6ba3d252675ef364ea",
          "sha1": "9f84fb61a87c16c853ae59faf12e21b02622ec8a",
          "md5": "c9e83a1f8ca779a9de8dd8ea4abcc3cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.4.3-sources.jar",
          "url": "spring-security-core-6.4.3-sources.jar",
          "size": 578209,
          "sha512": "99e692f5f95dd9b3a00160d27957dab34232405e3b9979b8f520fa12e7e4c8d08e98d01b7dc8830f288192a1b82a7be53de9a9e1907b6f42fffb737d3ed36779",
          "sha256": "5b540a0f3f263c4ed59cf6015b35b360658504a3ec9c1e2c061fd28b005a4b7a",
          "sha1": "3eff638735c09c51c1954b89774f1edf713b613f",
          "md5": "ed36886b0c2ecf0c854b07bce101a6e9"
        },
        {
          "name": "spring-security-core-6.4.3-sources.jar",
          "url": "spring-security-core-6.4.3-sources.jar",
          "size": 578209,
          "sha512": "99e692f5f95dd9b3a00160d27957dab34232405e3b9979b8f520fa12e7e4c8d08e98d01b7dc8830f288192a1b82a7be53de9a9e1907b6f42fffb737d3ed36779",
          "sha256": "5b540a0f3f263c4ed59cf6015b35b360658504a3ec9c1e2c061fd28b005a4b7a",
          "sha1": "3eff638735c09c51c1954b89774f1edf713b613f",
          "md5": "ed36886b0c2ecf0c854b07bce101a6e9"
        }
      ]
    }
  ]
}
