{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.7.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.25"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.9.jar",
          "url": "spring-boot-starter-2.7.9.jar",
          "size": 4770,
          "sha512": "cf6a1c5268441f03f4203d4f5498b5b33c46530a89c693a4b5005b2605419d3501e1b6c8e03b2b5cd4b085c9587f51c0a708cf968a642ab0018e8b57085e05c8",
          "sha256": "3275ad2338945e8105dc7793a35279918c36c3b0fa00c6c1b4e647f442c9296b",
          "sha1": "19f855d327f68690cf630698e4e41c3afe134a83",
          "md5": "69b5cea6bf131664e4273d7fb65abe45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.9"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.25"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.9.jar",
          "url": "spring-boot-starter-2.7.9.jar",
          "size": 4770,
          "sha512": "cf6a1c5268441f03f4203d4f5498b5b33c46530a89c693a4b5005b2605419d3501e1b6c8e03b2b5cd4b085c9587f51c0a708cf968a642ab0018e8b57085e05c8",
          "sha256": "3275ad2338945e8105dc7793a35279918c36c3b0fa00c6c1b4e647f442c9296b",
          "sha1": "19f855d327f68690cf630698e4e41c3afe134a83",
          "md5": "69b5cea6bf131664e4273d7fb65abe45"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.9.jar",
          "url": "spring-boot-starter-2.7.9.jar",
          "size": 4770,
          "sha512": "cf6a1c5268441f03f4203d4f5498b5b33c46530a89c693a4b5005b2605419d3501e1b6c8e03b2b5cd4b085c9587f51c0a708cf968a642ab0018e8b57085e05c8",
          "sha256": "3275ad2338945e8105dc7793a35279918c36c3b0fa00c6c1b4e647f442c9296b",
          "sha1": "19f855d327f68690cf630698e4e41c3afe134a83",
          "md5": "69b5cea6bf131664e4273d7fb65abe45"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.9.jar",
          "url": "spring-boot-starter-2.7.9.jar",
          "size": 4770,
          "sha512": "cf6a1c5268441f03f4203d4f5498b5b33c46530a89c693a4b5005b2605419d3501e1b6c8e03b2b5cd4b085c9587f51c0a708cf968a642ab0018e8b57085e05c8",
          "sha256": "3275ad2338945e8105dc7793a35279918c36c3b0fa00c6c1b4e647f442c9296b",
          "sha1": "19f855d327f68690cf630698e4e41c3afe134a83",
          "md5": "69b5cea6bf131664e4273d7fb65abe45"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.9-javadoc.jar",
          "url": "spring-boot-starter-2.7.9-javadoc.jar",
          "size": 4739,
          "sha512": "3e3772b54ccdaca9f3f747fa588e5e8ab96793603e0cb306915a23c9749921e2011f29f204c22755d4faf01a2cfb4c4a251e17804c7043ae9d8cdfef3407b592",
          "sha256": "5fb59a628b15a964c060540b973df03be9a0ab363e700198a5f2a9653e25c0f4",
          "sha1": "10230a569a7ace9c141b25111753a19895e0a0ec",
          "md5": "1e969efebc7649ee157ba541d80a9ada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.9-sources.jar",
          "url": "spring-boot-starter-2.7.9-sources.jar",
          "size": 4737,
          "sha512": "9cc12d1df4269ffdf5f73698b9945c7722d553d1f347bbe3694a11371d5a58a3d8079b5d2e3622b3072a3135797936b41b074b5be1830608c6a5536ce5417ab0",
          "sha256": "864653f72fed812b46680290462403beb0bb3e8471d5e75a0551e4d84b285633",
          "sha1": "4a4c93de254ed8686e92d0b43cab3f6595c77f92",
          "md5": "7d4ef7cc40075d6d42548969501110df"
        }
      ]
    }
  ]
}
