{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-6.2.3.jar",
          "url": "spring-jcl-6.2.3.jar",
          "size": 24539,
          "sha512": "49f0018727440d2c63c5e9e96115dac1137ed7f08b3195d300ff317749ee780b26252dc6acffa6c80211ee7c2d01a8852a93ecd6d7feb3f3200a11b0813092b5",
          "sha256": "8c65ec5ed648966a470e6b48b27cbebf5f1f412bd46b243e0111c5d5d96efe86",
          "sha1": "ce8bf55aa240fdeab07b3da1f462c79112a33aff",
          "md5": "07c72ae0ba752b93c493e95d8f4c8aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-6.2.3.jar",
          "url": "spring-jcl-6.2.3.jar",
          "size": 24539,
          "sha512": "49f0018727440d2c63c5e9e96115dac1137ed7f08b3195d300ff317749ee780b26252dc6acffa6c80211ee7c2d01a8852a93ecd6d7feb3f3200a11b0813092b5",
          "sha256": "8c65ec5ed648966a470e6b48b27cbebf5f1f412bd46b243e0111c5d5d96efe86",
          "sha1": "ce8bf55aa240fdeab07b3da1f462c79112a33aff",
          "md5": "07c72ae0ba752b93c493e95d8f4c8aae"
        }
      ]
    }
  ]
}
