{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.3.jar",
          "url": "spring-aspects-6.2.3.jar",
          "size": 49860,
          "sha512": "5ea6871f2e6a24b871a886e5987c580013ca5051dad4552e5fa7e08dfb3fec72bef3b49f45d716681a526e2ee68448c367cb80f71ac1bf62c5543a215ce7c8db",
          "sha256": "ef1b75b21f66692799fb0417f21d9a66bccdad5c284dfa7b1a914f24354b6cc7",
          "sha1": "f90a794dd3f81a1addc0552bc091e3f85b2428de",
          "md5": "063e56253a71509386b06f4037cdb2b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.3.jar",
          "url": "spring-aspects-6.2.3.jar",
          "size": 49860,
          "sha512": "5ea6871f2e6a24b871a886e5987c580013ca5051dad4552e5fa7e08dfb3fec72bef3b49f45d716681a526e2ee68448c367cb80f71ac1bf62c5543a215ce7c8db",
          "sha256": "ef1b75b21f66692799fb0417f21d9a66bccdad5c284dfa7b1a914f24354b6cc7",
          "sha1": "f90a794dd3f81a1addc0552bc091e3f85b2428de",
          "md5": "063e56253a71509386b06f4037cdb2b2"
        }
      ]
    }
  ]
}
