{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.3.jar",
          "url": "spring-security-crypto-6.4.3.jar",
          "size": 100745,
          "sha512": "91cf7a320e76fd647ce5b4f3cf28ebefad922c5ddf7fa524af7b45b273c2bbb4b68196e86f9c4938ce036bef2d4400d5d1be198fa43e3a4b95840fe03f4cc11b",
          "sha256": "3db113c5693aabca87895e55a4355a5917495759c71b5abb9d3e851f73c9d41c",
          "sha1": "157bf3d0173f12882938e244ba5c1359d72908d9",
          "md5": "cadd5040104725be97a383a2c66f4c03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.3.jar",
          "url": "spring-security-crypto-6.4.3.jar",
          "size": 100745,
          "sha512": "91cf7a320e76fd647ce5b4f3cf28ebefad922c5ddf7fa524af7b45b273c2bbb4b68196e86f9c4938ce036bef2d4400d5d1be198fa43e3a4b95840fe03f4cc11b",
          "sha256": "3db113c5693aabca87895e55a4355a5917495759c71b5abb9d3e851f73c9d41c",
          "sha1": "157bf3d0173f12882938e244ba5c1359d72908d9",
          "md5": "cadd5040104725be97a383a2c66f4c03"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.3-javadoc.jar",
          "url": "spring-security-crypto-6.4.3-javadoc.jar",
          "size": 241592,
          "sha512": "bbfca918e81a4e24de62f192e4eaa8a75439656c1d72748bb3acc41bae2eb249fbba8e4e48571ab50bd907b7dbee5d1502ba378c9bee4d03334cd27b1f4adcce",
          "sha256": "f6bef88793b5d2423900a27ab060f75365044767969a95191cf21d2dd4931516",
          "sha1": "70050c622e30f6081becfbffe66e1722229e0825",
          "md5": "40a68dfe2cc6c5d81e708f6a59c6234d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.4.3-sources.jar",
          "url": "spring-security-crypto-6.4.3-sources.jar",
          "size": 86716,
          "sha512": "3ab1ea6f2c69d024f4bcacb8e48e4dffafe40a1d64c1eba129f25f53fbad3d9bdb0453189276def99bbe33e44c0436eb353f1505252ec167f2f9f86e6442eba6",
          "sha256": "f0b0a6fae93100161c0a2f20c80478f68e3d8fe49bb4f9084bed0ded11feb631",
          "sha1": "87a469bed925ff4f9e7a04fab88149711d5850d0",
          "md5": "d84e173e2d59748d369074c563d482ec"
        }
      ]
    }
  ]
}
