{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.4.3.jar",
          "url": "spring-security-config-6.4.3.jar",
          "size": 2024913,
          "sha512": "a4d9f09d3536f2246d5fa4fbe47f32835dae54524ab8b636aa1404a21967cb356e43a40274926d42e150857bb0380f75debcbbc833fe41dce1f33e4af1789897",
          "sha256": "807d636c5877b71154b4fbe2dd6c7c23801ca303b9cb18e3493f9f46870067b2",
          "sha1": "052d7cedfde4f9a4e78f27b754e8be89ec25e871",
          "md5": "7ec7deaac249fadbe14acdb63063715d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.4.3.jar",
          "url": "spring-security-config-6.4.3.jar",
          "size": 2024913,
          "sha512": "a4d9f09d3536f2246d5fa4fbe47f32835dae54524ab8b636aa1404a21967cb356e43a40274926d42e150857bb0380f75debcbbc833fe41dce1f33e4af1789897",
          "sha256": "807d636c5877b71154b4fbe2dd6c7c23801ca303b9cb18e3493f9f46870067b2",
          "sha1": "052d7cedfde4f9a4e78f27b754e8be89ec25e871",
          "md5": "7ec7deaac249fadbe14acdb63063715d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.4.3-javadoc.jar",
          "url": "spring-security-config-6.4.3-javadoc.jar",
          "size": 1171635,
          "sha512": "e4958d1c97c7ad3c99c2eee6b40950feba2753b5315edb0658992271ff9b0465545d15858600cd30c4dfa420957d0e3dcebf1746a7b4be4f6804ce8957a57033",
          "sha256": "5888717a9ca5861ff19d99906420833a49aaf87ac1d66e3d927fff722442569a",
          "sha1": "cf5de8f260e579123144c1b1e986c2b02d196551",
          "md5": "97378b8d30d496ba0bb35098b8aac386"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.4.3-sources.jar",
          "url": "spring-security-config-6.4.3-sources.jar",
          "size": 1384431,
          "sha512": "f776ccddf8819f091df657c5c2949bcaa4e5cdc47abd8957b4aa8bb590576c4d337ba74f2983b14fe68fd62cb2037c25ce9e31bda0f3be77f0e2c114f6a844a7",
          "sha256": "8edecf6b955bebe7ac93674d2f7c164437adea174e0cb00d29df1f4b94a61e5e",
          "sha1": "6c737a87304a514702e9e9d3ff4c658261f5bbea",
          "md5": "88be6c2d2156169d6b781912285aad7b"
        },
        {
          "name": "spring-security-config-6.4.3-sources.jar",
          "url": "spring-security-config-6.4.3-sources.jar",
          "size": 1384431,
          "sha512": "f776ccddf8819f091df657c5c2949bcaa4e5cdc47abd8957b4aa8bb590576c4d337ba74f2983b14fe68fd62cb2037c25ce9e31bda0f3be77f0e2c114f6a844a7",
          "sha256": "8edecf6b955bebe7ac93674d2f7c164437adea174e0cb00d29df1f4b94a61e5e",
          "sha1": "6c737a87304a514702e9e9d3ff4c658261f5bbea",
          "md5": "88be6c2d2156169d6b781912285aad7b"
        }
      ]
    }
  ]
}
